#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

export KPT_TRANSPORT_MODEL="${KPT_TRANSPORT_MODEL:-parker}"
export KPT_BENCHMARK_ROOT="${KPT_BENCHMARK_ROOT:-${REPO_ROOT}/benchmark_runs/reconnection_optimized_200}"
export KPT_FORTRAN_BUILD_MODE="${KPT_FORTRAN_BUILD_MODE:-avx512}"
export KPT_CPU_CORES="${KPT_CPU_CORES:-16}"
export KPT_BUILD_JOBS="${KPT_BUILD_JOBS:-${KPT_CPU_CORES}}"
export KPT_MPI_SIZE="${KPT_MPI_SIZE:-${KPT_CPU_CORES}}"
export KPT_KOKKOS_CPU_THREADS="${KPT_KOKKOS_CPU_THREADS:-${KPT_CPU_CORES}}"
export KPT_KOKKOS_GPU_HOST_THREADS="${KPT_KOKKOS_GPU_HOST_THREADS:-1}"
export KPT_CPU_CXX_FLAGS="${KPT_CPU_CXX_FLAGS:--O3 -march=native}"
export KPT_START_FRAME="${KPT_START_FRAME:-0}"
export KPT_END_FRAME="${KPT_END_FRAME:-200}"
export KPT_HISTOGRAM_INTERVAL="${KPT_HISTOGRAM_INTERVAL:-10}"
export KPT_PARTICLES_PER_RANK="${KPT_PARTICLES_PER_RANK:-1600}"
export KPT_CXX_PARTICLE_CAPACITY="${KPT_CXX_PARTICLE_CAPACITY:-16000000}"
export KPT_FORTRAN_PARTICLE_CAPACITY="${KPT_FORTRAN_PARTICLE_CAPACITY:-1000000}"

exec "${SCRIPT_DIR}/run_reconnection_three_cases.sh" "$@"
